spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/magic?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      pool-name: sweet-toolset-data-pool
      minimum-idle: 10 # 最小空闲连接数
      idle-timeout: 600000 # 空闲连接存活最大时间
      maximum-pool-size: 20 # 连接池最大连接数
      auto-commit: true # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000
  data:
    redis:
      database: 0
      port: 6379
      password:
      timeout: 300000ms
      lettuce:
        pool:
          max-active: 8 #连接池最大连接数
          max-idle: 8 #连接池最大空闲连接数
          min-idle: 0 #连接池最小空闲连接数
          max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制

  servlet:
    multipart:
      enabled: true # 是否开启文件上传，默认为true
      max-file-size: 10MB # 单个文件上传的最大上限
      max-request-size: 10MB # 一次请求总大小上限